"""replace skill catalog tables with plain skills columns

Revision ID: 92ce2d7587b4
Revises: c616862ee920
Create Date: 2026-09-15 15:17:39.978372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ce2d7587b4'
down_revision: Union[str, Sequence[str], None] = 'c616862ee920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_skills')
    op.drop_table('job_skills')
    op.drop_table('freelancer_skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.add_column(
        'freelancer_profiles',
        sa.Column('skills', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.add_column('jobs', sa.Column('skills', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    op.add_column(
        'proposals', sa.Column('skills', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'skills')
    op.drop_column('jobs', 'skills')
    op.drop_column('freelancer_profiles', 'skills')
    op.create_table('skills',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey'))
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('freelancer_skills',
    sa.Column('freelancer_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], name=op.f('freelancer_skills_freelancer_profile_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('freelancer_skills_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('freelancer_profile_id', 'skill_id', name=op.f('freelancer_skills_pkey'))
    )
    op.create_table('job_skills',
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_skills_job_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('job_skills_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id', name=op.f('job_skills_pkey'))
    )
    op.create_table('proposal_skills',
    sa.Column('proposal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('proposal_skills_proposal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('proposal_skills_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposal_id', 'skill_id', name=op.f('proposal_skills_pkey'))
    )
    # ### end Alembic commands ###
