"""add attachments table, migrate avatar and contract document to attachments

Revision ID: c616862ee920
Revises: a5871d3828ab
Create Date: 2026-09-14 18:13:21.077339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c616862ee920'
down_revision: Union[str, Sequence[str], None] = 'a5871d3828ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('JOB', 'PROPOSAL', 'CONTRACT', 'MILESTONE', 'PROFILE', name='attachmentresourcetype', native_enum=False), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'checksum', name='uq_resource_checksum'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_attachments_owner_id'), 'attachments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_attachments_resource_id'), 'attachments', ['resource_id'], unique=False)
    op.create_index(op.f('ix_attachments_resource_type'), 'attachments', ['resource_type'], unique=False)
    op.drop_column('contracts', 'document_url')
    op.add_column('freelancer_profiles', sa.Column('avatar_attachment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'freelancer_profiles', 'attachments', ['avatar_attachment_id'], ['id'], ondelete='SET NULL')
    op.drop_column('freelancer_profiles', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_profiles', sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'freelancer_profiles', type_='foreignkey')
    op.drop_column('freelancer_profiles', 'avatar_attachment_id')
    op.add_column('contracts', sa.Column('document_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_attachments_resource_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_resource_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_owner_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
